name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-16.04'
  demands:
  - npm
  - node.js
  - java

steps:
- task: NodeTool@0
  displayName: 'Install Node.Js'
  inputs:
    versionSpec: 10.x
    checkLatest: true
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Gulp@0
  displayName: 'Increase version number in package-solution.json'
  inputs:
    targets: bump-version

- task: Gulp@0
  displayName: 'Bundle project'
  inputs:
    targets: bundle
    arguments: '--ship'

- task: Gulp@0
  displayName: 'Package Solution'
  inputs:
    targets: 'package-solution'
    arguments: '--ship'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     config/package-solution.json
     sharepoint/solution/*.sppkg
     PowerShell/**/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'